apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-control-plane
  namespace: exp
  labels:
    k8s-app: ftmesh
spec:
  selector:
    matchLabels:
      k8s-app: ftmesh
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: ftmesh
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - name: controller
        image: go-control-plane:latest
        ports:
        - containerPort: 10901
          name: control
        resources:
          requests:
            vcpu: "1"
            memory: 2Gi
          limits:
            vcpu: "1"
            memory: 4Gi           		
